/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SignupRouteImport } from "./routes/signup";
import { Route as SigninRouteImport } from "./routes/signin";
import { Route as ImportRouteImport } from "./routes/import";
import { Route as ImageOcclusionRouteImport } from "./routes/image-occlusion";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as CreateRouteImport } from "./routes/create";
import { Route as AiGenerateRouteImport } from "./routes/ai-generate";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as PublicIdRouteImport } from "./routes/public.$id";
import { Route as LegalTermsRouteImport } from "./routes/legal.terms";
import { Route as LegalPrivacyRouteImport } from "./routes/legal.privacy";
import { Route as FolderIdRouteImport } from "./routes/folder.$id";
import { Route as ClassIdRouteImport } from "./routes/class.$id";
import { Route as AuthCallbackRouteImport } from "./routes/auth.callback";
import { Route as ApiDashboardRouteImport } from "./routes/api/dashboard";
import { Route as ApiCardMetadataRouteImport } from "./routes/api/card-metadata";
import { Route as ApiAnalyticsRouteImport } from "./routes/api/analytics";
import { Route as SetIdIndexRouteImport } from "./routes/set.$id.index";
import { Route as SetIdWriteRouteImport } from "./routes/set.$id.write";
import { Route as SetIdTestRouteImport } from "./routes/set.$id.test";
import { Route as SetIdMatchRouteImport } from "./routes/set.$id.match";
import { Route as SetIdLearnRouteImport } from "./routes/set.$id.learn";
import { Route as SetIdFlashcardsRouteImport } from "./routes/set.$id.flashcards";
import { Route as SetIdEditRouteImport } from "./routes/set.$id.edit";
import { Route as ApiSetsSearchRouteImport } from "./routes/api/sets.search";
import { Route as ApiSetsIdRouteImport } from "./routes/api/sets.$id";
import { Route as ApiFoldersIdRouteImport } from "./routes/api/folders.$id";
import { Route as ApiClassesIdRouteImport } from "./routes/api/classes.$id";
import { Route as ApiSetsIdExportCsvRouteImport } from "./routes/api/sets.$id.export.csv";

const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any);
const SigninRoute = SigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => rootRouteImport,
} as any);
const ImportRoute = ImportRouteImport.update({
  id: "/import",
  path: "/import",
  getParentRoute: () => rootRouteImport,
} as any);
const ImageOcclusionRoute = ImageOcclusionRouteImport.update({
  id: "/image-occlusion",
  path: "/image-occlusion",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateRoute = CreateRouteImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => rootRouteImport,
} as any);
const AiGenerateRoute = AiGenerateRouteImport.update({
  id: "/ai-generate",
  path: "/ai-generate",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const PublicIdRoute = PublicIdRouteImport.update({
  id: "/public/$id",
  path: "/public/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: "/legal/terms",
  path: "/legal/terms",
  getParentRoute: () => rootRouteImport,
} as any);
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: "/legal/privacy",
  path: "/legal/privacy",
  getParentRoute: () => rootRouteImport,
} as any);
const FolderIdRoute = FolderIdRouteImport.update({
  id: "/folder/$id",
  path: "/folder/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const ClassIdRoute = ClassIdRouteImport.update({
  id: "/class/$id",
  path: "/class/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: "/auth/callback",
  path: "/auth/callback",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: "/api/dashboard",
  path: "/api/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiCardMetadataRoute = ApiCardMetadataRouteImport.update({
  id: "/api/card-metadata",
  path: "/api/card-metadata",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: "/api/analytics",
  path: "/api/analytics",
  getParentRoute: () => rootRouteImport,
} as any);
const SetIdIndexRoute = SetIdIndexRouteImport.update({
  id: "/set/$id/",
  path: "/set/$id/",
  getParentRoute: () => rootRouteImport,
} as any);
const SetIdWriteRoute = SetIdWriteRouteImport.update({
  id: "/set/$id/write",
  path: "/set/$id/write",
  getParentRoute: () => rootRouteImport,
} as any);
const SetIdTestRoute = SetIdTestRouteImport.update({
  id: "/set/$id/test",
  path: "/set/$id/test",
  getParentRoute: () => rootRouteImport,
} as any);
const SetIdMatchRoute = SetIdMatchRouteImport.update({
  id: "/set/$id/match",
  path: "/set/$id/match",
  getParentRoute: () => rootRouteImport,
} as any);
const SetIdLearnRoute = SetIdLearnRouteImport.update({
  id: "/set/$id/learn",
  path: "/set/$id/learn",
  getParentRoute: () => rootRouteImport,
} as any);
const SetIdFlashcardsRoute = SetIdFlashcardsRouteImport.update({
  id: "/set/$id/flashcards",
  path: "/set/$id/flashcards",
  getParentRoute: () => rootRouteImport,
} as any);
const SetIdEditRoute = SetIdEditRouteImport.update({
  id: "/set/$id/edit",
  path: "/set/$id/edit",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSetsSearchRoute = ApiSetsSearchRouteImport.update({
  id: "/api/sets/search",
  path: "/api/sets/search",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSetsIdRoute = ApiSetsIdRouteImport.update({
  id: "/api/sets/$id",
  path: "/api/sets/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiFoldersIdRoute = ApiFoldersIdRouteImport.update({
  id: "/api/folders/$id",
  path: "/api/folders/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiClassesIdRoute = ApiClassesIdRouteImport.update({
  id: "/api/classes/$id",
  path: "/api/classes/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSetsIdExportCsvRoute = ApiSetsIdExportCsvRouteImport.update({
  id: "/export/csv",
  path: "/export/csv",
  getParentRoute: () => ApiSetsIdRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/ai-generate": typeof AiGenerateRoute;
  "/create": typeof CreateRoute;
  "/dashboard": typeof DashboardRoute;
  "/image-occlusion": typeof ImageOcclusionRoute;
  "/import": typeof ImportRoute;
  "/signin": typeof SigninRoute;
  "/signup": typeof SignupRoute;
  "/api/analytics": typeof ApiAnalyticsRoute;
  "/api/card-metadata": typeof ApiCardMetadataRoute;
  "/api/dashboard": typeof ApiDashboardRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/class/$id": typeof ClassIdRoute;
  "/folder/$id": typeof FolderIdRoute;
  "/legal/privacy": typeof LegalPrivacyRoute;
  "/legal/terms": typeof LegalTermsRoute;
  "/public/$id": typeof PublicIdRoute;
  "/api/classes/$id": typeof ApiClassesIdRoute;
  "/api/folders/$id": typeof ApiFoldersIdRoute;
  "/api/sets/$id": typeof ApiSetsIdRouteWithChildren;
  "/api/sets/search": typeof ApiSetsSearchRoute;
  "/set/$id/edit": typeof SetIdEditRoute;
  "/set/$id/flashcards": typeof SetIdFlashcardsRoute;
  "/set/$id/learn": typeof SetIdLearnRoute;
  "/set/$id/match": typeof SetIdMatchRoute;
  "/set/$id/test": typeof SetIdTestRoute;
  "/set/$id/write": typeof SetIdWriteRoute;
  "/set/$id/": typeof SetIdIndexRoute;
  "/api/sets/$id/export/csv": typeof ApiSetsIdExportCsvRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/ai-generate": typeof AiGenerateRoute;
  "/create": typeof CreateRoute;
  "/dashboard": typeof DashboardRoute;
  "/image-occlusion": typeof ImageOcclusionRoute;
  "/import": typeof ImportRoute;
  "/signin": typeof SigninRoute;
  "/signup": typeof SignupRoute;
  "/api/analytics": typeof ApiAnalyticsRoute;
  "/api/card-metadata": typeof ApiCardMetadataRoute;
  "/api/dashboard": typeof ApiDashboardRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/class/$id": typeof ClassIdRoute;
  "/folder/$id": typeof FolderIdRoute;
  "/legal/privacy": typeof LegalPrivacyRoute;
  "/legal/terms": typeof LegalTermsRoute;
  "/public/$id": typeof PublicIdRoute;
  "/api/classes/$id": typeof ApiClassesIdRoute;
  "/api/folders/$id": typeof ApiFoldersIdRoute;
  "/api/sets/$id": typeof ApiSetsIdRouteWithChildren;
  "/api/sets/search": typeof ApiSetsSearchRoute;
  "/set/$id/edit": typeof SetIdEditRoute;
  "/set/$id/flashcards": typeof SetIdFlashcardsRoute;
  "/set/$id/learn": typeof SetIdLearnRoute;
  "/set/$id/match": typeof SetIdMatchRoute;
  "/set/$id/test": typeof SetIdTestRoute;
  "/set/$id/write": typeof SetIdWriteRoute;
  "/set/$id": typeof SetIdIndexRoute;
  "/api/sets/$id/export/csv": typeof ApiSetsIdExportCsvRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/ai-generate": typeof AiGenerateRoute;
  "/create": typeof CreateRoute;
  "/dashboard": typeof DashboardRoute;
  "/image-occlusion": typeof ImageOcclusionRoute;
  "/import": typeof ImportRoute;
  "/signin": typeof SigninRoute;
  "/signup": typeof SignupRoute;
  "/api/analytics": typeof ApiAnalyticsRoute;
  "/api/card-metadata": typeof ApiCardMetadataRoute;
  "/api/dashboard": typeof ApiDashboardRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/class/$id": typeof ClassIdRoute;
  "/folder/$id": typeof FolderIdRoute;
  "/legal/privacy": typeof LegalPrivacyRoute;
  "/legal/terms": typeof LegalTermsRoute;
  "/public/$id": typeof PublicIdRoute;
  "/api/classes/$id": typeof ApiClassesIdRoute;
  "/api/folders/$id": typeof ApiFoldersIdRoute;
  "/api/sets/$id": typeof ApiSetsIdRouteWithChildren;
  "/api/sets/search": typeof ApiSetsSearchRoute;
  "/set/$id/edit": typeof SetIdEditRoute;
  "/set/$id/flashcards": typeof SetIdFlashcardsRoute;
  "/set/$id/learn": typeof SetIdLearnRoute;
  "/set/$id/match": typeof SetIdMatchRoute;
  "/set/$id/test": typeof SetIdTestRoute;
  "/set/$id/write": typeof SetIdWriteRoute;
  "/set/$id/": typeof SetIdIndexRoute;
  "/api/sets/$id/export/csv": typeof ApiSetsIdExportCsvRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/ai-generate"
    | "/create"
    | "/dashboard"
    | "/image-occlusion"
    | "/import"
    | "/signin"
    | "/signup"
    | "/api/analytics"
    | "/api/card-metadata"
    | "/api/dashboard"
    | "/auth/callback"
    | "/class/$id"
    | "/folder/$id"
    | "/legal/privacy"
    | "/legal/terms"
    | "/public/$id"
    | "/api/classes/$id"
    | "/api/folders/$id"
    | "/api/sets/$id"
    | "/api/sets/search"
    | "/set/$id/edit"
    | "/set/$id/flashcards"
    | "/set/$id/learn"
    | "/set/$id/match"
    | "/set/$id/test"
    | "/set/$id/write"
    | "/set/$id/"
    | "/api/sets/$id/export/csv";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/ai-generate"
    | "/create"
    | "/dashboard"
    | "/image-occlusion"
    | "/import"
    | "/signin"
    | "/signup"
    | "/api/analytics"
    | "/api/card-metadata"
    | "/api/dashboard"
    | "/auth/callback"
    | "/class/$id"
    | "/folder/$id"
    | "/legal/privacy"
    | "/legal/terms"
    | "/public/$id"
    | "/api/classes/$id"
    | "/api/folders/$id"
    | "/api/sets/$id"
    | "/api/sets/search"
    | "/set/$id/edit"
    | "/set/$id/flashcards"
    | "/set/$id/learn"
    | "/set/$id/match"
    | "/set/$id/test"
    | "/set/$id/write"
    | "/set/$id"
    | "/api/sets/$id/export/csv";
  id:
    | "__root__"
    | "/"
    | "/ai-generate"
    | "/create"
    | "/dashboard"
    | "/image-occlusion"
    | "/import"
    | "/signin"
    | "/signup"
    | "/api/analytics"
    | "/api/card-metadata"
    | "/api/dashboard"
    | "/auth/callback"
    | "/class/$id"
    | "/folder/$id"
    | "/legal/privacy"
    | "/legal/terms"
    | "/public/$id"
    | "/api/classes/$id"
    | "/api/folders/$id"
    | "/api/sets/$id"
    | "/api/sets/search"
    | "/set/$id/edit"
    | "/set/$id/flashcards"
    | "/set/$id/learn"
    | "/set/$id/match"
    | "/set/$id/test"
    | "/set/$id/write"
    | "/set/$id/"
    | "/api/sets/$id/export/csv";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AiGenerateRoute: typeof AiGenerateRoute;
  CreateRoute: typeof CreateRoute;
  DashboardRoute: typeof DashboardRoute;
  ImageOcclusionRoute: typeof ImageOcclusionRoute;
  ImportRoute: typeof ImportRoute;
  SigninRoute: typeof SigninRoute;
  SignupRoute: typeof SignupRoute;
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute;
  ApiCardMetadataRoute: typeof ApiCardMetadataRoute;
  ApiDashboardRoute: typeof ApiDashboardRoute;
  AuthCallbackRoute: typeof AuthCallbackRoute;
  ClassIdRoute: typeof ClassIdRoute;
  FolderIdRoute: typeof FolderIdRoute;
  LegalPrivacyRoute: typeof LegalPrivacyRoute;
  LegalTermsRoute: typeof LegalTermsRoute;
  PublicIdRoute: typeof PublicIdRoute;
  ApiClassesIdRoute: typeof ApiClassesIdRoute;
  ApiFoldersIdRoute: typeof ApiFoldersIdRoute;
  ApiSetsIdRoute: typeof ApiSetsIdRouteWithChildren;
  ApiSetsSearchRoute: typeof ApiSetsSearchRoute;
  SetIdEditRoute: typeof SetIdEditRoute;
  SetIdFlashcardsRoute: typeof SetIdFlashcardsRoute;
  SetIdLearnRoute: typeof SetIdLearnRoute;
  SetIdMatchRoute: typeof SetIdMatchRoute;
  SetIdTestRoute: typeof SetIdTestRoute;
  SetIdWriteRoute: typeof SetIdWriteRoute;
  SetIdIndexRoute: typeof SetIdIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/signup": {
      id: "/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/signin": {
      id: "/signin";
      path: "/signin";
      fullPath: "/signin";
      preLoaderRoute: typeof SigninRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/import": {
      id: "/import";
      path: "/import";
      fullPath: "/import";
      preLoaderRoute: typeof ImportRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/image-occlusion": {
      id: "/image-occlusion";
      path: "/image-occlusion";
      fullPath: "/image-occlusion";
      preLoaderRoute: typeof ImageOcclusionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create": {
      id: "/create";
      path: "/create";
      fullPath: "/create";
      preLoaderRoute: typeof CreateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/ai-generate": {
      id: "/ai-generate";
      path: "/ai-generate";
      fullPath: "/ai-generate";
      preLoaderRoute: typeof AiGenerateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/public/$id": {
      id: "/public/$id";
      path: "/public/$id";
      fullPath: "/public/$id";
      preLoaderRoute: typeof PublicIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/legal/terms": {
      id: "/legal/terms";
      path: "/legal/terms";
      fullPath: "/legal/terms";
      preLoaderRoute: typeof LegalTermsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/legal/privacy": {
      id: "/legal/privacy";
      path: "/legal/privacy";
      fullPath: "/legal/privacy";
      preLoaderRoute: typeof LegalPrivacyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/folder/$id": {
      id: "/folder/$id";
      path: "/folder/$id";
      fullPath: "/folder/$id";
      preLoaderRoute: typeof FolderIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/class/$id": {
      id: "/class/$id";
      path: "/class/$id";
      fullPath: "/class/$id";
      preLoaderRoute: typeof ClassIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/callback": {
      id: "/auth/callback";
      path: "/auth/callback";
      fullPath: "/auth/callback";
      preLoaderRoute: typeof AuthCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/dashboard": {
      id: "/api/dashboard";
      path: "/api/dashboard";
      fullPath: "/api/dashboard";
      preLoaderRoute: typeof ApiDashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/card-metadata": {
      id: "/api/card-metadata";
      path: "/api/card-metadata";
      fullPath: "/api/card-metadata";
      preLoaderRoute: typeof ApiCardMetadataRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/analytics": {
      id: "/api/analytics";
      path: "/api/analytics";
      fullPath: "/api/analytics";
      preLoaderRoute: typeof ApiAnalyticsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/set/$id/": {
      id: "/set/$id/";
      path: "/set/$id";
      fullPath: "/set/$id/";
      preLoaderRoute: typeof SetIdIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/set/$id/write": {
      id: "/set/$id/write";
      path: "/set/$id/write";
      fullPath: "/set/$id/write";
      preLoaderRoute: typeof SetIdWriteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/set/$id/test": {
      id: "/set/$id/test";
      path: "/set/$id/test";
      fullPath: "/set/$id/test";
      preLoaderRoute: typeof SetIdTestRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/set/$id/match": {
      id: "/set/$id/match";
      path: "/set/$id/match";
      fullPath: "/set/$id/match";
      preLoaderRoute: typeof SetIdMatchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/set/$id/learn": {
      id: "/set/$id/learn";
      path: "/set/$id/learn";
      fullPath: "/set/$id/learn";
      preLoaderRoute: typeof SetIdLearnRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/set/$id/flashcards": {
      id: "/set/$id/flashcards";
      path: "/set/$id/flashcards";
      fullPath: "/set/$id/flashcards";
      preLoaderRoute: typeof SetIdFlashcardsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/set/$id/edit": {
      id: "/set/$id/edit";
      path: "/set/$id/edit";
      fullPath: "/set/$id/edit";
      preLoaderRoute: typeof SetIdEditRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/sets/search": {
      id: "/api/sets/search";
      path: "/api/sets/search";
      fullPath: "/api/sets/search";
      preLoaderRoute: typeof ApiSetsSearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/sets/$id": {
      id: "/api/sets/$id";
      path: "/api/sets/$id";
      fullPath: "/api/sets/$id";
      preLoaderRoute: typeof ApiSetsIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/folders/$id": {
      id: "/api/folders/$id";
      path: "/api/folders/$id";
      fullPath: "/api/folders/$id";
      preLoaderRoute: typeof ApiFoldersIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/classes/$id": {
      id: "/api/classes/$id";
      path: "/api/classes/$id";
      fullPath: "/api/classes/$id";
      preLoaderRoute: typeof ApiClassesIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/sets/$id/export/csv": {
      id: "/api/sets/$id/export/csv";
      path: "/export/csv";
      fullPath: "/api/sets/$id/export/csv";
      preLoaderRoute: typeof ApiSetsIdExportCsvRouteImport;
      parentRoute: typeof ApiSetsIdRoute;
    };
  }
}

interface ApiSetsIdRouteChildren {
  ApiSetsIdExportCsvRoute: typeof ApiSetsIdExportCsvRoute;
}

const ApiSetsIdRouteChildren: ApiSetsIdRouteChildren = {
  ApiSetsIdExportCsvRoute: ApiSetsIdExportCsvRoute,
};

const ApiSetsIdRouteWithChildren = ApiSetsIdRoute._addFileChildren(
  ApiSetsIdRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiGenerateRoute: AiGenerateRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  ImageOcclusionRoute: ImageOcclusionRoute,
  ImportRoute: ImportRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiCardMetadataRoute: ApiCardMetadataRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ClassIdRoute: ClassIdRoute,
  FolderIdRoute: FolderIdRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  PublicIdRoute: PublicIdRoute,
  ApiClassesIdRoute: ApiClassesIdRoute,
  ApiFoldersIdRoute: ApiFoldersIdRoute,
  ApiSetsIdRoute: ApiSetsIdRouteWithChildren,
  ApiSetsSearchRoute: ApiSetsSearchRoute,
  SetIdEditRoute: SetIdEditRoute,
  SetIdFlashcardsRoute: SetIdFlashcardsRoute,
  SetIdLearnRoute: SetIdLearnRoute,
  SetIdMatchRoute: SetIdMatchRoute,
  SetIdTestRoute: SetIdTestRoute,
  SetIdWriteRoute: SetIdWriteRoute,
  SetIdIndexRoute: SetIdIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
